spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/meubairro
spring.datasource.username=postgres
spring.datasource.password=metas
spring.jpa.show-sql=true

upload.dir=uploads
 # URL base da API (ajustar para producao)
upload.base-url=http://localhost:8080
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=50MB

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT Configuration
jwt.secret=sua_chave_secreta_muito_segura_aqui_minimo_256_bits_recomendado
jwt.expiration=86400000

# Spring Security
spring.security.user.name=admin
spring.security.user.password=admin123

